name: Build Vulkan WSI Layer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vulkan SDK dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl lsb-release gnupg

    - name: Add Vulkan repository
      run: |
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:kisak/kisak-mesa

    - name: Install Vulkan SDK
      run: |
        sudo apt update
        sudo apt install -y vulkan-utils

    - name: Install build dependencies
      run: |
        sudo apt install -y cmake build-essential

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build the project
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests (optional)
      run: |
        cd build
        make test
