name: Build Vulkan WSI Layer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl lsb-release gnupg software-properties-common cmake build-essential

    - name: Add LunarG Vulkan SDK repository
      run: |
        curl -fsSL https://packages.lunarg.com/lunarg-signing-key.asc | gpg --dearmor -o /usr/share/keyrings/lunarg-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/lunarg-archive-keyring.gpg] https://packages.lunarg.com/vulkan/ubuntu $(lsb_release -c | awk '{print $2}') main" | sudo tee /etc/apt/sources.list.d/lunarg-vulkan.list

    - name: Install Vulkan SDK
      run: |
        sudo apt update
        sudo apt install -y vulkan-sdk

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build the project
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests (optional)
      run: |
        cd build
        make test
