name: Build Vulkan WSI Layer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vulkan SDK dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl lsb-release gnupg

    - name: Add Vulkan SDK repository
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key.asc | sudo apt-key add -
        sudo apt-add-repository "deb https://packages.lunarg.com/vulkan/ubuntu $(lsb_release -c | awk '{print $2}') main"

    - name: Install Vulkan SDK
      run: |
        sudo apt update
        sudo apt install -y vulkan-sdk

    - name: Install build dependencies
      run: |
        sudo apt install -y cmake build-essential

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build the project
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests (optional)
      run: |
        cd build
        make test
